import type { AiGenerationResult, BuilderFile } from "@/types/project";
import { slugify, titleFromPrompt } from "@/lib/utils";

export function generateDeterministicSite(prompt: string): AiGenerationResult {
  const title = titleFromPrompt(prompt);
  const slug = slugify(title) || "generated-site";
  const product = title.replace(/\.$/, "");

  const files: BuilderFile[] = [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `import { Hero } from "@/components/hero";
import { FeatureGrid } from "@/components/feature-grid";
import { Pricing } from "@/components/pricing";

export default function Page() {
  return (
    <main className="min-h-screen bg-[#101210] text-[#f7fbf5]">
      <Hero />
      <FeatureGrid />
      <Pricing />
    </main>
  );
}
`,
    },
    {
      path: "components/hero.tsx",
      language: "tsx",
      content: `export function Hero() {
  return (
    <section className="mx-auto grid min-h-screen max-w-6xl place-items-center px-6 py-24 text-center">
      <div>
        <p className="mx-auto w-max rounded-full border border-[#9af5a7]/25 bg-[#9af5a7]/10 px-3 py-1 text-sm text-[#d9ffe0]">
          Generated by Forge
        </p>
        <h1 className="mt-8 text-6xl font-semibold leading-none">
          ${product} built for teams that ship.
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#aeb9ac]">
          ${prompt}
        </p>
        <div className="mt-10 flex justify-center gap-3">
          <a className="rounded-md bg-[#9af5a7] px-5 py-3 font-semibold text-[#102112]" href="#pricing">
            Start free
          </a>
          <a className="rounded-md border border-white/10 px-5 py-3 font-semibold" href="#features">
            See features
          </a>
        </div>
      </div>
    </section>
  );
}
`,
    },
    {
      path: "components/feature-grid.tsx",
      language: "tsx",
      content: `const features = [
  "AI-generated section architecture",
  "Responsive Tailwind component system",
  "Project history and code export",
  "GitHub and Vercel-ready workflow",
];

export function FeatureGrid() {
  return (
    <section id="features" className="mx-auto grid max-w-6xl gap-4 px-6 py-24 md:grid-cols-2">
      {features.map((feature) => (
        <article key={feature} className="rounded-lg border border-white/10 bg-white/[0.035] p-6">
          <h2 className="text-xl font-semibold">{feature}</h2>
          <p className="mt-3 text-sm leading-6 text-[#aeb9ac]">
            Designed for production teams that need clean code, fast iteration, and polished UX.
          </p>
        </article>
      ))}
    </section>
  );
}
`,
    },
    {
      path: "components/pricing.tsx",
      language: "tsx",
      content: `const plans = ["Starter", "Pro", "Team"];

export function Pricing() {
  return (
    <section id="pricing" className="mx-auto max-w-6xl px-6 py-24">
      <h2 className="text-center text-4xl font-semibold">Plans for every build phase.</h2>
      <div className="mt-12 grid gap-4 md:grid-cols-3">
        {plans.map((plan, index) => (
          <article key={plan} className="rounded-lg border border-white/10 bg-white/[0.035] p-6">
            <h3 className="text-xl font-semibold">{plan}</h3>
            <div className="mt-5 text-4xl font-semibold">$\${[0, 19, 49][index]}</div>
            <p className="mt-4 text-sm leading-6 text-[#aeb9ac]">
              Includes AI edits, responsive previews, export, versioning, and deployment workflows.
            </p>
          </article>
        ))}
      </div>
    </section>
  );
}
`,
    },
    {
      path: "README.md",
      language: "md",
      content: `# ${product}

Generated by Forge from:

${prompt}

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
    },
  ];

  return {
    summary: `Generated ${files.length} files for ${product}.`,
    files,
    steps: [
      { name: "Planner", status: "Complete", detail: "Mapped the site goals, routes, sections, and conversion path." },
      { name: "UI generator", status: "Complete", detail: "Created the page shell and responsive component hierarchy." },
      { name: "Component generator", status: "Complete", detail: "Generated React component files with reusable structure." },
      { name: "Styling agent", status: "Complete", detail: "Applied dark premium tokens and Tailwind classes." },
      { name: "Debug agent", status: "Complete", detail: "Checked imports, file paths, and deployment notes." },
    ],
  };
}
